name: hoist
favicon: null
layout_spectrum: 1
typography_spectrum: 0.33904
title: 'hoist!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#8c8c8c'
    - '#a9a9a9'
    - '#0f0f0f'
    - '#4d4d4d'
  brandStrength: 0.875
  lightness: 0.25
  saturation: 0.8071918559726328
  rhythmicContrast: 1
purpose: []
